# Site/SEO settings
email: matejthetree@gmail.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: Art Nomad Project
title: Art Nomad Project
description: >
  travel and create
url: https://www.artnomadproject.net
#twitter_username: thomasvaeth
default_img: /assets/images/seo.jpg
social:
  - name: facebook
    url: https://www.facebook.com/artnomadproject
  - name: instagram
    url: https://www.instagram.com/artnomadproject/
#  - name: linkedin
#    url: https://www.linkedin.com/in/thomasvaeth/
#  - name: github
#    url: https://github.com/samesies
#  - name: codepen
#    url: https://codepen.io/thomasvaeth/

# Contact settings
contact_img: /assets/images/grad-prazan.jpg
formcarry: https://formcarry.com/s/aMdYLtgI79U


# Disqus settings
disqus: artnomadproject-com

# MailChimp settings
mailchimp_action: https://artnomadproject.us19.list-manage.com/subscribe/post-json?u=5ab1895e8fb180aed0ac6591e&amp;id=a5569c92b6
mailchimp_input: b_5ab1895e8fb180aed0ac6591e_a5569c92b6

# Author settings
author:
  - name: Matej Šimunić
    bio: digitalni nomad, zaljubljenik u umjetnost i strastveni putnik.
    url: http://matejthetree.github.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

#Jekyll-Photo-Gallery Settings
exiftag:
  sources:
  - images/photography #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
  photography:
    source: images/photography
    destination: images/photography/thumbnails
    resize: "1280x720"
  headers:
    source: images/headers
    destination: images/headers/thumbnails
    resize: "400x250"


compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
